<a href="https://colab.research.google.com/github/4nands/L20251022/blob/main/L20251030.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import matplotlib.pyplot as plt

def onehot(x):

  k=np.max(x)+1
  y = np.identity(k)

  return y[x]

def softmax(x):

  c = np.max(x,axis=-1,keepdims=True)
  e = np.exp(x-c)
  z = np.sum(e,axis=-1,keepdims=True)

  return e/z


class Sigmoid:

  def __init__(self):

    self.out = None

  def __call__(self,x):

    y = 1/(1+np.exp(-x))
    self.out = y

    return y

  def backward(self,dout):

    return self.out * (1-self.out)

class Linear:

  def __init__(self,d_in,d_out):

    self.W = np.random.randn(d_in,d_out)
    self.b = np.zeros(d_out)

    self.dW = np.zeros_like(self.W)
    self.db = np.zeros_like(self.b)

    self.inputs = None

  def __call__(self,x):

    self.inputs = x

    y = x @ self.W + self.b

    return y


  def backward(self,dout):

    self.dW = self.inputs.T @ dout
    self.db = np.sum(dout)

    return dout @ self.W.T

  def optimizer(self,lr=0.1):

    self.W -= lr * self.dW
    self.b -= lr * self.db


class MLP:

  def __init__(self,d_in,d_h,d_out):

    self.l1 = Linear(d_in,d_h)
    self.a = Sigmoid()
    self.l2 = Linear(d_h,d_out)

  def __call__(self,x):

    x = self.l1(x)
    x = self.a(x)
    x = self.l2(x)

    return x

  def pred(self,x):

    out = self(x)

    return np.argmax(out,axis=-1)


x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,1,2,3])

y = onehot(y)

d_in = x.shape[1]
d_h = 4*d_in
d_out = y.shape[1]

model = MLP(d_in,d_h,d_out)
pred = model.pred(x)
print(pred)



[1 1 1 1]


In [22]:
x = np.array([[10,20,30],[-5,6,7],[0.1,100,0.5]])
print(x)
c = np.max(x,axis=-1,keepdims=True)
e = np.exp(x-c)
z = np.sum(e,axis=-1,keepdims=True)

out = e/z


[[ 10.   20.   30. ]
 [ -5.    6.    7. ]
 [  0.1 100.    0.5]]
[[ 10.   20.   30. ]
 [ -5.    6.    7. ]
 [  0.1 100.    0.5]]
[[1.0000454 ]
 [1.36788559]
 [1.        ]]
[[2.06106005e-09 4.53978686e-05 9.99954600e-01]
 [4.49175897e-06 2.68940213e-01 7.31055295e-01]
 [4.11131978e-44 1.00000000e+00 6.13336839e-44]]


In [27]:
x = np.array([[1,2,3],[-2,6,7],[5,4,3]])
print(np.max(x,axis=-1))
print(np.argmax(x,axis=-1))


[3 7 5]
[2 2 0]
